export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const POST_POKEMON = "POST_POKEMON";
export const GET_ALL_TYPES = "GET_ALL_TYPES";
export const DELETE_POKEMON = "DELETE_POKEMON";
export const DELETE_POKEMON_API = "DELETE_POKEMON_API"
export const FROM_API_EXTERNAL = "FROM_API_EXTERNAL";
export const FROM_DATA_BASE = "FROM_DATA_BASE";

